sudo: required
dist: trusty

language: haxe

os:
  - linux
#  - osx

haxe:
  - "3.2.1"
  - development
 
matrix:
  allow_failures:
    - haxe: development
    
install:
  - haxelib install travix
  - haxelib run travix install

script:
  - openfl test flash
  - openfl test html5
  - openfl test cpp